// Mock data for the examination platform — will be replaced with real API calls

export const mockUsers = [
     {
          _id: 'admin1',
          name: 'Dr. Sarah Admin',
          email: 'admin@quizora.com',
          password: 'admin123',
          role: 'admin',
          createdAt: '2024-01-15T10:00:00Z',
     },
     {
          _id: 'student1',
          name: 'Alex Johnson',
          email: 'alex@student.com',
          password: 'student123',
          role: 'student',
          createdAt: '2024-02-01T10:00:00Z',
     },
     {
          _id: 'student2',
          name: 'Emily Chen',
          email: 'emily@student.com',
          password: 'student123',
          role: 'student',
          createdAt: '2024-02-05T10:00:00Z',
     },
     {
          _id: 'student3',
          name: 'Raj Patel',
          email: 'raj@student.com',
          password: 'student123',
          role: 'student',
          createdAt: '2024-02-10T10:00:00Z',
     },
]

export const mockTests = [
     {
          _id: 'test1',
          title: 'Data Structures & Algorithms',
          description: 'Comprehensive test covering arrays, linked lists, trees, graphs, sorting and searching algorithms.',
          duration: 60,
          totalMarks: 100,
          negativeMarking: 0.25,
          shuffleQuestions: true,
          shuffleOptions: true,
          startDate: '2024-01-01T00:00:00Z',
          endDate: '2026-12-31T23:59:59Z',
          createdBy: 'admin1',
          questionsCount: 10,
          isPublished: true,
          status: 'active',
     },
     {
          _id: 'test2',
          title: 'Web Development Fundamentals',
          description: 'Test your knowledge of HTML, CSS, JavaScript, React, and modern web development practices.',
          duration: 45,
          totalMarks: 75,
          negativeMarking: 0,
          shuffleQuestions: false,
          shuffleOptions: true,
          startDate: '2024-01-01T00:00:00Z',
          endDate: '2026-12-31T23:59:59Z',
          createdBy: 'admin1',
          questionsCount: 8,
          isPublished: true,
          status: 'active',
     },
     {
          _id: 'test3',
          title: 'Database Management Systems',
          description: 'SQL, NoSQL, normalization, indexing and database design principles.',
          duration: 30,
          totalMarks: 50,
          negativeMarking: 0.5,
          shuffleQuestions: true,
          shuffleOptions: false,
          startDate: '2024-06-01T00:00:00Z',
          endDate: '2026-06-30T23:59:59Z',
          createdBy: 'admin1',
          questionsCount: 5,
          isPublished: false,
          status: 'active',
     },
     {
          _id: 'test4',
          title: 'Operating Systems',
          description: 'Process management, memory management, file systems and concurrency.',
          duration: 90,
          totalMarks: 150,
          negativeMarking: 0.33,
          shuffleQuestions: true,
          shuffleOptions: true,
          startDate: '2025-01-01T00:00:00Z',
          endDate: '2025-03-01T00:00:00Z',
          createdBy: 'admin1',
          questionsCount: 6,
          isPublished: false,
          status: 'expired',
     },
]

export const mockQuestions = {
     test1: [
          { _id: 'q1', testId: 'test1', questionText: 'What is the time complexity of binary search?', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correctAnswer: 1, marks: 10 },
          { _id: 'q2', testId: 'test1', questionText: 'Which data structure uses FIFO principle?', options: ['Stack', 'Queue', 'Array', 'Tree'], correctAnswer: 1, marks: 10 },
          { _id: 'q3', testId: 'test1', questionText: 'What is the worst case time complexity of quicksort?', options: ['O(n log n)', 'O(n)', 'O(n²)', 'O(log n)'], correctAnswer: 2, marks: 10 },
          { _id: 'q4', testId: 'test1', questionText: 'Which traversal gives sorted order in BST?', options: ['Preorder', 'Postorder', 'Inorder', 'Level order'], correctAnswer: 2, marks: 10 },
          { _id: 'q5', testId: 'test1', questionText: 'What is the space complexity of merge sort?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], correctAnswer: 2, marks: 10 },
          { _id: 'q6', testId: 'test1', questionText: 'Which algorithm is used to find shortest path in a weighted graph?', options: ['BFS', 'DFS', 'Dijkstra', 'Prim\'s'], correctAnswer: 2, marks: 10 },
          { _id: 'q7', testId: 'test1', questionText: 'What data structure is used in BFS?', options: ['Stack', 'Queue', 'Heap', 'Array'], correctAnswer: 1, marks: 10 },
          { _id: 'q8', testId: 'test1', questionText: 'What is a complete binary tree?', options: ['All nodes have 2 children', 'All levels full except possibly last', 'All leaves at same level', 'Height is log n'], correctAnswer: 1, marks: 10 },
          { _id: 'q9', testId: 'test1', questionText: 'Hash table average case lookup is?', options: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'], correctAnswer: 2, marks: 10 },
          { _id: 'q10', testId: 'test1', questionText: 'Which sorting algorithm is stable?', options: ['Quick Sort', 'Heap Sort', 'Merge Sort', 'Selection Sort'], correctAnswer: 2, marks: 10 },
     ],
     test2: [
          { _id: 'q11', testId: 'test2', questionText: 'What does CSS stand for?', options: ['Cascading Style Sheets', 'Creative Style System', 'Computer Style Sheets', 'Colorful Style Sheets'], correctAnswer: 0, marks: 10 },
          { _id: 'q12', testId: 'test2', questionText: 'Which HTML tag is used for the largest heading?', options: ['<heading>', '<h6>', '<h1>', '<head>'], correctAnswer: 2, marks: 10 },
          { _id: 'q13', testId: 'test2', questionText: 'What is the virtual DOM in React?', options: ['A real DOM copy', 'A lightweight JS representation of the DOM', 'A browser API', 'A CSS framework'], correctAnswer: 1, marks: 10 },
          { _id: 'q14', testId: 'test2', questionText: 'Which method is used to update state in React hooks?', options: ['this.setState()', 'useState()', 'setState()', 'The setter function from useState'], correctAnswer: 3, marks: 10 },
          { _id: 'q15', testId: 'test2', questionText: 'What is the box model in CSS?', options: ['A 3D rendering model', 'Content + Padding + Border + Margin', 'A layout framework', 'A grid system'], correctAnswer: 1, marks: 10 },
          { _id: 'q16', testId: 'test2', questionText: 'What does "use strict" do in JavaScript?', options: ['Makes code faster', 'Enables strict mode with stricter parsing', 'Disables console.log', 'Enables TypeScript'], correctAnswer: 1, marks: 10 },
          { _id: 'q17', testId: 'test2', questionText: 'Which HTTP method is used to update a resource?', options: ['GET', 'POST', 'PUT', 'DELETE'], correctAnswer: 2, marks: 5 },
          { _id: 'q18', testId: 'test2', questionText: 'What is JSX?', options: ['A JavaScript library', 'JavaScript XML syntax extension', 'A CSS preprocessor', 'A Node.js framework'], correctAnswer: 1, marks: 10 },
     ],
     test3: [
          { _id: 'q19', testId: 'test3', questionText: 'What is normalization in databases?', options: ['Adding redundancy', 'Removing redundancy', 'Encrypting data', 'Compressing data'], correctAnswer: 1, marks: 10 },
          { _id: 'q20', testId: 'test3', questionText: 'Which SQL command is used to retrieve data?', options: ['GET', 'FETCH', 'SELECT', 'RETRIEVE'], correctAnswer: 2, marks: 10 },
          { _id: 'q21', testId: 'test3', questionText: 'What is a primary key?', options: ['Any column', 'A unique identifier for each row', 'A foreign reference', 'An index'], correctAnswer: 1, marks: 10 },
          { _id: 'q22', testId: 'test3', questionText: 'MongoDB is what type of database?', options: ['Relational', 'Graph', 'Document-based NoSQL', 'Key-value'], correctAnswer: 2, marks: 10 },
          { _id: 'q23', testId: 'test3', questionText: 'What does ACID stand for in databases?', options: ['Atomicity Consistency Isolation Durability', 'Add Create Insert Delete', 'Access Control Identity Data', 'None of these'], correctAnswer: 0, marks: 10 },
     ],
     test4: [
          { _id: 'q24', testId: 'test4', questionText: 'What is a process in OS?', options: ['A file', 'A program in execution', 'A thread', 'A driver'], correctAnswer: 1, marks: 25 },
          { _id: 'q25', testId: 'test4', questionText: 'What is virtual memory?', options: ['RAM extension using disk', 'Cloud storage', 'Cache memory', 'ROM'], correctAnswer: 0, marks: 25 },
          { _id: 'q26', testId: 'test4', questionText: 'Which scheduling algorithm has convoy effect?', options: ['Round Robin', 'FCFS', 'SJF', 'Priority'], correctAnswer: 1, marks: 25 },
          { _id: 'q27', testId: 'test4', questionText: 'What is a deadlock?', options: ['Fast execution', 'Circular wait among processes', 'Memory overflow', 'CPU idle state'], correctAnswer: 1, marks: 25 },
          { _id: 'q28', testId: 'test4', questionText: 'What is thrashing?', options: ['Fast paging', 'Excessive paging causing low CPU utilization', 'Cache hit', 'Disk defrag'], correctAnswer: 1, marks: 25 },
          { _id: 'q29', testId: 'test4', questionText: 'Which is not an OS?', options: ['Windows', 'Linux', 'Oracle', 'macOS'], correctAnswer: 2, marks: 25 },
     ],
}

export const mockAttempts = [
     {
          _id: 'att1',
          studentId: 'student1',
          studentName: 'Alex Johnson',
          testId: 'test1',
          testTitle: 'Data Structures & Algorithms',
          answers: { q1: 1, q2: 1, q3: 2, q4: 2, q5: 0, q6: 2, q7: 1, q8: 1, q9: 2, q10: 2 },
          score: 85,
          totalMarks: 100,
          tabSwitchCount: 1,
          suspiciousLogs: [{ type: 'tab_switch', timestamp: '2024-03-01T10:15:00Z', count: 1 }],
          startedAt: '2024-03-01T10:00:00Z',
          submittedAt: '2024-03-01T10:45:00Z',
          percentage: 85,
     },
     {
          _id: 'att2',
          studentId: 'student2',
          studentName: 'Emily Chen',
          testId: 'test1',
          testTitle: 'Data Structures & Algorithms',
          answers: { q1: 1, q2: 1, q3: 2, q4: 2, q5: 2, q6: 2, q7: 1, q8: 1, q9: 2, q10: 2 },
          score: 92.5,
          totalMarks: 100,
          tabSwitchCount: 0,
          suspiciousLogs: [],
          startedAt: '2024-03-02T14:00:00Z',
          submittedAt: '2024-03-02T14:50:00Z',
          percentage: 92.5,
     },
     {
          _id: 'att3',
          studentId: 'student3',
          studentName: 'Raj Patel',
          testId: 'test1',
          testTitle: 'Data Structures & Algorithms',
          answers: { q1: 1, q2: 0, q3: 2, q4: 1, q5: 2, q6: 2, q7: 1, q8: 0, q9: 2, q10: 0 },
          score: 62.5,
          totalMarks: 100,
          tabSwitchCount: 3,
          suspiciousLogs: [
               { type: 'tab_switch', timestamp: '2024-03-03T09:10:00Z', count: 1 },
               { type: 'tab_switch', timestamp: '2024-03-03T09:20:00Z', count: 2 },
               { type: 'fullscreen_exit', timestamp: '2024-03-03T09:22:00Z' },
               { type: 'tab_switch', timestamp: '2024-03-03T09:25:00Z', count: 3 },
          ],
          startedAt: '2024-03-03T09:00:00Z',
          submittedAt: '2024-03-03T09:30:00Z',
          percentage: 62.5,
     },
     {
          _id: 'att4',
          studentId: 'student1',
          studentName: 'Alex Johnson',
          testId: 'test2',
          testTitle: 'Web Development Fundamentals',
          answers: { q11: 0, q12: 2, q13: 1, q14: 3, q15: 1, q16: 1, q17: 2, q18: 1 },
          score: 75,
          totalMarks: 75,
          tabSwitchCount: 0,
          suspiciousLogs: [],
          startedAt: '2024-03-05T11:00:00Z',
          submittedAt: '2024-03-05T11:30:00Z',
          percentage: 100,
     },
     {
          _id: 'att5',
          studentId: 'student2',
          studentName: 'Emily Chen',
          testId: 'test2',
          testTitle: 'Web Development Fundamentals',
          answers: { q11: 0, q12: 2, q13: 1, q14: 3, q15: 1, q16: 0, q17: 2, q18: 1 },
          score: 65,
          totalMarks: 75,
          tabSwitchCount: 1,
          suspiciousLogs: [{ type: 'tab_switch', timestamp: '2024-03-06T15:15:00Z', count: 1 }],
          startedAt: '2024-03-06T15:00:00Z',
          submittedAt: '2024-03-06T15:40:00Z',
          percentage: 86.7,
     },
]
